BEGIN;

CREATE TABLE IF NOT EXISTS lab_services (id UUID PRIMARY KEY, branch_id UUID REFERENCES branches(id), name TEXT NOT NULL, category TEXT NOT NULL DEFAULT '', price NUMERIC(12,2) NOT NULL DEFAULT 0, duration_minutes INTEGER NOT NULL DEFAULT 0, reference_range TEXT NOT NULL DEFAULT '', active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS lab_orders (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), branch_id UUID REFERENCES branches(id), patient_id TEXT NOT NULL, doctor_id TEXT, visit_id TEXT, appointment_id TEXT, priority TEXT NOT NULL DEFAULT 'normal', notes TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'requested', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS lab_order_items (id UUID PRIMARY KEY, order_id UUID NOT NULL REFERENCES lab_orders(id) ON DELETE CASCADE, service_id UUID REFERENCES lab_services(id), test_name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'requested');
CREATE TABLE IF NOT EXISTS lab_samples (id UUID PRIMARY KEY, order_id UUID NOT NULL REFERENCES lab_orders(id) ON DELETE CASCADE, sample_code TEXT NOT NULL UNIQUE, sample_type TEXT NOT NULL DEFAULT '', collected_at TIMESTAMPTZ, collected_by TEXT, status TEXT NOT NULL DEFAULT 'waiting');
CREATE TABLE IF NOT EXISTS lab_results (id UUID PRIMARY KEY, order_item_id UUID NOT NULL REFERENCES lab_order_items(id) ON DELETE CASCADE, value TEXT NOT NULL DEFAULT '', unit TEXT NOT NULL DEFAULT '', reference_range TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', technician_id TEXT, reviewer_id TEXT, status TEXT NOT NULL DEFAULT 'draft', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS lab_result_files (id UUID PRIMARY KEY, result_id UUID NOT NULL REFERENCES lab_results(id) ON DELETE CASCADE, storage_key TEXT NOT NULL, mime_type TEXT NOT NULL, size_bytes BIGINT NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS medicines (id UUID PRIMARY KEY, name TEXT NOT NULL, active_ingredient TEXT NOT NULL DEFAULT '', form TEXT NOT NULL DEFAULT '', strength TEXT NOT NULL DEFAULT '', barcode TEXT NOT NULL DEFAULT '', manufacturer TEXT NOT NULL DEFAULT '', unit TEXT NOT NULL DEFAULT '', active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS dispensing (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), branch_id UUID REFERENCES branches(id), patient_id TEXT NOT NULL, prescription_id TEXT NOT NULL, doctor_id TEXT, pharmacist_id TEXT, status TEXT NOT NULL DEFAULT 'pending', notes TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS dispensing_items (id UUID PRIMARY KEY, dispensing_id UUID NOT NULL REFERENCES dispensing(id) ON DELETE CASCADE, medicine_id UUID NOT NULL REFERENCES medicines(id), prescribed_quantity NUMERIC(12,3) NOT NULL DEFAULT 0, dispensed_quantity NUMERIC(12,3) NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS inventory_items (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), branch_id UUID REFERENCES branches(id), sku TEXT NOT NULL, barcode TEXT NOT NULL DEFAULT '', name TEXT NOT NULL, category TEXT NOT NULL DEFAULT '', unit TEXT NOT NULL DEFAULT '', minimum_quantity NUMERIC(12,3) NOT NULL DEFAULT 0, maximum_quantity NUMERIC(12,3), reorder_level NUMERIC(12,3) NOT NULL DEFAULT 0, UNIQUE (organization_id, sku));
CREATE TABLE IF NOT EXISTS inventory_categories (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), name TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE (organization_id, name));
CREATE TABLE IF NOT EXISTS warehouses (id UUID PRIMARY KEY, branch_id UUID NOT NULL REFERENCES branches(id), name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS suppliers (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), name TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '', email TEXT NOT NULL DEFAULT '', active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS purchase_orders (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), branch_id UUID REFERENCES branches(id), supplier_id UUID REFERENCES suppliers(id), status TEXT NOT NULL DEFAULT 'draft', created_by TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS purchase_order_items (id UUID PRIMARY KEY, purchase_order_id UUID NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE, item_id UUID NOT NULL REFERENCES inventory_items(id), quantity NUMERIC(12,3) NOT NULL DEFAULT 0, unit_cost NUMERIC(12,2) NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS stock_batches (id UUID PRIMARY KEY, item_id UUID NOT NULL REFERENCES inventory_items(id), warehouse_id UUID NOT NULL REFERENCES warehouses(id), batch_number TEXT NOT NULL, quantity NUMERIC(12,3) NOT NULL DEFAULT 0, purchase_date DATE, expiry_date DATE, cost NUMERIC(12,2) NOT NULL DEFAULT 0, supplier_id UUID);
CREATE TABLE IF NOT EXISTS stock_movements (id UUID PRIMARY KEY, item_id UUID NOT NULL REFERENCES inventory_items(id), batch_id UUID REFERENCES stock_batches(id), source_warehouse_id UUID REFERENCES warehouses(id), destination_warehouse_id UUID REFERENCES warehouses(id), quantity NUMERIC(12,3) NOT NULL, movement_type TEXT NOT NULL CHECK (movement_type IN ('IN','OUT','TRANSFER','ADJUSTMENT','RETURN')), user_id TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS inventory_adjustments (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), branch_id UUID REFERENCES branches(id), warehouse_id UUID REFERENCES warehouses(id), item_id UUID NOT NULL REFERENCES inventory_items(id), quantity_delta NUMERIC(12,3) NOT NULL, reason TEXT NOT NULL, created_by TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS inventory_transfers (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), source_warehouse_id UUID NOT NULL REFERENCES warehouses(id), destination_warehouse_id UUID NOT NULL REFERENCES warehouses(id), status TEXT NOT NULL DEFAULT 'requested', created_by TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

CREATE TABLE IF NOT EXISTS radiology_services (id UUID PRIMARY KEY, branch_id UUID REFERENCES branches(id), name TEXT NOT NULL, price NUMERIC(12,2) NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS radiology_orders (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), branch_id UUID REFERENCES branches(id), patient_id TEXT NOT NULL, doctor_id TEXT, visit_id TEXT, study TEXT NOT NULL, indication TEXT NOT NULL DEFAULT '', priority TEXT NOT NULL DEFAULT 'normal', status TEXT NOT NULL DEFAULT 'requested', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS radiology_reports (id UUID PRIMARY KEY, order_id UUID NOT NULL REFERENCES radiology_orders(id) ON DELETE CASCADE, findings TEXT NOT NULL DEFAULT '', impression TEXT NOT NULL DEFAULT '', radiologist_id TEXT, status TEXT NOT NULL DEFAULT 'draft', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS radiology_files (id UUID PRIMARY KEY, report_id UUID NOT NULL REFERENCES radiology_reports(id) ON DELETE CASCADE, storage_key TEXT NOT NULL, mime_type TEXT NOT NULL, size_bytes BIGINT NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS procedures (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), branch_id UUID REFERENCES branches(id), patient_id TEXT NOT NULL, doctor_id TEXT, appointment_id TEXT, procedure_type TEXT NOT NULL, scheduled_at TIMESTAMPTZ, status TEXT NOT NULL DEFAULT 'scheduled', diagnosis TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', outcome TEXT NOT NULL DEFAULT '', follow_up TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS procedure_attachments (id UUID PRIMARY KEY, procedure_id UUID NOT NULL REFERENCES procedures(id) ON DELETE CASCADE, storage_key TEXT NOT NULL, mime_type TEXT NOT NULL, size_bytes BIGINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS call_logs (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), branch_id UUID REFERENCES branches(id), patient_id TEXT, phone TEXT NOT NULL DEFAULT '', agent_id TEXT, call_type TEXT NOT NULL, result TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', called_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ambulances (id UUID PRIMARY KEY, branch_id UUID REFERENCES branches(id), vehicle_number TEXT NOT NULL, plate_number TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'available', equipment_notes TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS ambulance_crews (id UUID PRIMARY KEY, ambulance_id UUID NOT NULL REFERENCES ambulances(id) ON DELETE CASCADE, user_id TEXT NOT NULL, role TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ambulance_requests (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), branch_id UUID REFERENCES branches(id), patient_id TEXT, caller_name TEXT NOT NULL, caller_phone TEXT NOT NULL, location_text TEXT NOT NULL, emergency_type TEXT NOT NULL, priority TEXT NOT NULL DEFAULT 'normal', status TEXT NOT NULL DEFAULT 'requested', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ambulance_dispatches (id UUID PRIMARY KEY, request_id UUID NOT NULL REFERENCES ambulance_requests(id), ambulance_id UUID REFERENCES ambulances(id), crew JSONB NOT NULL DEFAULT '[]'::jsonb, dispatched_at TIMESTAMPTZ, arrived_at TIMESTAMPTZ, picked_up_at TIMESTAMPTZ, destination_arrived_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, notes TEXT NOT NULL DEFAULT '');

CREATE TABLE IF NOT EXISTS notification_templates (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), event_key TEXT NOT NULL, channel TEXT NOT NULL, body TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS notification_rules (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), event_key TEXT NOT NULL, minutes_before INTEGER NOT NULL DEFAULT 0, channel TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS notification_deliveries (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), user_id TEXT NOT NULL, event_key TEXT NOT NULL, channel TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued', provider_message_id TEXT, error TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS reminders (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), branch_id UUID REFERENCES branches(id), user_id TEXT NOT NULL, event_key TEXT NOT NULL, due_at TIMESTAMPTZ NOT NULL, status TEXT NOT NULL DEFAULT 'queued');

COMMIT;
